### ISSUE TITLE
PDF - Net::HTTPNotFound for http://www.stonnington.vic.gov.au/PlanningRegister.aspx?PageID=567

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/stonnington#2]
```
/app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:304:in `fetch' : 404 => Net::HTTPNotFound for http://www.stonnington.vic.gov.au/PlanningRegister.aspx?PageID=567 -- unhandled response (Mechanize::ResponseCodeError)
 	from /app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
 	from scraper.rb:7:in `<main>'
```

```
The City of Stonnington's new website
You are seeing this page because we have launched a brand new City of Stonnington website.  

Unfortunately your old bookmarks or favourited pages may no longer work. We apologise for the inconvenience but trust you will find this new website easier to use for all your Council related information. You can display our new website on any of your devices including your mobile phone or tablet.

Please resume your search by starting at our our homepage.  

If you require further assistance please email us at council@stonnington.vic.gov.au  or call 8290 1333.

Thank You.
```

New URL: http://www.stonnington.vic.gov.au/Development/Planning/Advertised-Material
Unfortunately its a pile of PDFs

Probably not worth rewriting yet due to
```
The Planning Register is currently offline. It will relaunch when we introduce our new online planning portal — ePlanning — later in the year.

ePlanning will allow users to submit planning applications, amendments, plans to comply, enquiries, objections and make payments as well as view documents and search the register for all planning applications in Stonnington online, anytime.

Watch this space ... ePlanning portal launching soon ...
```

**Comment by henare** [comment]
Sigh.

**Comment by e-e-e** [comment]
I emailed them:

> Hi,
> I was just curious when your new ePlanning Register will be available on the website? Your planing data was once accessible via www.planningalerts.org.au, but is no longer because the data is not on the council website any more.
> Kindest regards,

They replied:

> Thank you for your email to the City of Stonnington. Your email will be forwarded to the appropriate department for action. Should you require immediate attention you should call the City of Stonnington Service Centre on 8290 1333.
> 
>  
> 
> If your correspondence is related to a parking infringement, please be advised your email has been forwarded to the Stonnington Parking Alliance for action.  Should you require any additional details please call 9200 8215 or visit the Stonnington Parking Alliance (click here).
>  
> Should you require any additional information or assistance, don’t hesitate to contact the City of Stonnington Service Centres at Prahran and Malvern Town Halls and at the Tooronga Road Depot by clicking here.  We are here to assist you in person 8:30am to 5:00pm Monday to Friday or please call 8290 1333. 
>  
> Other news and information on the City of Stonnington can be found on our website by clicking here and you can keep up to date on the latest news and information by following us on Facebook and Twitter.
>  
> You can expect to receive a response to your email soon.  Thank you for making contact with the City of Stonnington.
>

**Comment by JasonThomasData** [comment]
These guys have a new website, here - https://eplanning.stonnington.vic.gov.au/EPlanning/Public/PlanningRegister.aspx?search=basic

I just tried it though and this page uses JavaScript to render the results. 

I'mm most comfortable with Python so I'm going to use Python, Selenium and PhantomJS to scrape the new page.

**Comment by CloCkWeRX** [comment]
How'd you get on with this? Happy to help via slack/a google hangout/similiar

**Comment by JasonThomasData** [comment]
Hi @cloCkWerx, I atually forgot to email you back. I never did this is in the end.

**Comment by mnot** [comment]
See #3
